stages: [build, test, deploy]

include:
  - project: infercom-dev/devops
    file:
      - templates/rules.yml
      - templates/docker.yml
      - templates/test.yml
      - templates/deploy.yml

workflow:
  rules:
    # variables внутри этих вариантов могут уехать в переменные CI 
    # https://gitlab.infercom.one/infercom-dev/llm-chains/knowledge-pipeline/-/settings/ci_cd#js-cicd-variables-settings
    # поскольку в джобах environment:name: задан как $DEPLOY_ENVIRONMENT, то в джобы они попадут в зависимости от окружения,
    # без необходимости грузить их все разом
    - if: !reference [.workflow, develop, if]
      variables:
        DEPLOY_ENVIRONMENT: dev
        ENV_FILE:           $ENV_FILE_DEV
        HOST:               deploy-user@84.23.48.232
        FOLDER:             /data/llm_chains_dev/knowledge_pipeline_container
        DC:                 docker compose
        DEPLOY_APP_ENV_TARGET: config/.env
    - if: !reference [.workflow, stage, if]
      variables:
        DEPLOY_ENVIRONMENT: stage
        ENV_FILE:           $ENV_FILE_STAGE
        HOST:               deploy-user@84.23.48.232
        FOLDER:             /data/llm_chains/knowledge_pipeline_container
        DC:                 docker compose
        DEPLOY_APP_ENV_TARGET: config/.env
    - if: !reference [.workflow, production, if]
      variables:
        DEPLOY_ENVIRONMENT: prod
        ENV_FILE:           $ENV_FILE_PROD
        HOST:               deploy-user@84.23.48.231
        FOLDER:             /data/llm_chains/knowledge_pipeline_container
        DC:                 docker compose
        DEPLOY_APP_ENV_TARGET: config/.env
    # И в таком случае можно будет использовать просто вот такие конструкции
  # - !reference [.workflow, develop]
  # - !reference [.workflow, stage]
  # - !reference [.workflow, production]